# Generated by Django 5.2.4 on 2025-07-25 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("horses", "0003_remove_horse_foals_horse_children"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="horse",
            name="children",
        ),
        migrations.AddField(
            model_name="horse",
            name="children",
            field=models.ManyToManyField(
                related_name="parents", to="horses.horse", verbose_name="Дети"
            ),
        ),
    ]
