# Generated by Django 5.2.4 on 2025-08-25 16:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
        ('horses', '0005_horse_photos_alter_horse_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HorseOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, validators=[django.core.validators.MaxLengthValidator(50)], verbose_name='Наименование')),
                ('description', models.CharField(blank=True, max_length=500, null=True, validators=[django.core.validators.MaxLengthValidator(500)], verbose_name='Описание')),
                ('type', models.PositiveSmallIntegerField(choices=[(0, 'Юридическое лицо'), (1, 'Физическое лицо'), (2, 'Неизвестно')], default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)], verbose_name='Тип')),
                ('address', models.CharField(blank=True, max_length=150, null=True, validators=[django.core.validators.MaxLengthValidator(150)], verbose_name='Адрес')),
                ('phone_number', models.JSONField(default=list, verbose_name='Номера телефонов')),
            ],
        ),
        migrations.AlterModelOptions(
            name='horse',
            options={'ordering': ['name'], 'verbose_name': 'Лошадь', 'verbose_name_plural': 'Лошади'},
        ),
        migrations.AddField(
            model_name='horse',
            name='kind',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Лошадь'), (1, 'Пони')], default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Тип'),
        ),
        migrations.AddField(
            model_name='horse',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='horse', to='horses.horseowner', verbose_name='Владелец'),
        ),
        migrations.AddIndex(
            model_name='horse',
            index=models.Index(fields=['name'], name='horses_hors_name_914b5d_idx'),
        ),
        migrations.AddIndex(
            model_name='horse',
            index=models.Index(fields=['sex'], name='horses_hors_sex_112905_idx'),
        ),
        migrations.AddIndex(
            model_name='horse',
            index=models.Index(fields=['bdate'], name='horses_hors_bdate_704902_idx'),
        ),
        migrations.AddIndex(
            model_name='horse',
            index=models.Index(fields=['ddate'], name='horses_hors_ddate_a67fa3_idx'),
        ),
        migrations.AddIndex(
            model_name='horse',
            index=models.Index(fields=['breed'], name='horses_hors_breed_i_d2ceff_idx'),
        ),
    ]
