# Generated by Django 5.2.7 on 2025-10-18 16:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0001_initial"),
        ("horses", "0006_horseowner_alter_horse_options_horse_kind_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="breed",
            name="description",
            field=models.CharField(
                blank=True,
                max_length=500,
                null=True,
                validators=[
                    django.core.validators.MinLengthValidator(5),
                    django.core.validators.MaxLengthValidator(500),
                ],
                verbose_name="Описание",
            ),
        ),
        migrations.AlterField(
            model_name="breed",
            name="name",
            field=models.CharField(
                max_length=50,
                validators=[
                    django.core.validators.MinLengthValidator(5),
                    django.core.validators.MaxLengthValidator(50),
                ],
                verbose_name="Наименование",
            ),
        ),
        migrations.AlterField(
            model_name="horse",
            name="owner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="horses",
                to="horses.horseowner",
                verbose_name="Владелец",
            ),
        ),
        migrations.AlterField(
            model_name="horse",
            name="photos",
            field=models.ManyToManyField(
                related_name="horses", to="gallery.photo", verbose_name="Фотографии"
            ),
        ),
        migrations.AlterField(
            model_name="horseowner",
            name="address",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                validators=[django.core.validators.MaxLengthValidator(200)],
                verbose_name="Адрес",
            ),
        ),
        migrations.AlterField(
            model_name="horseowner",
            name="name",
            field=models.CharField(
                max_length=150,
                validators=[django.core.validators.MaxLengthValidator(150)],
                verbose_name="Наименование",
            ),
        ),
        migrations.AlterField(
            model_name="horseowner",
            name="phone_number",
            field=models.JSONField(
                blank=True, default=list, null=True, verbose_name="Номера телефонов"
            ),
        ),
    ]
