# Generated by Django 5.2.7 on 2025-10-18 16:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactsGroups",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=127,
                        unique=True,
                        validators=[django.core.validators.MaxLengthValidator(127)],
                        verbose_name="Наименование группы",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="KeyValueInformation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=127,
                        unique=True,
                        validators=[django.core.validators.MaxLengthValidator(127)],
                        verbose_name="Ключ информации для API",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=255,
                        validators=[django.core.validators.MaxLengthValidator(255)],
                        verbose_name="Человекочитаемое наименование",
                    ),
                ),
                ("value", models.CharField(verbose_name="Значение")),
                (
                    "as_type",
                    models.CharField(
                        max_length=31,
                        validators=[django.core.validators.MaxLengthValidator(31)],
                        verbose_name="Тип данных",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Contacts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "main_title",
                    models.CharField(
                        max_length=127,
                        validators=[django.core.validators.MaxLengthValidator(127)],
                        verbose_name="Первичное наименование",
                    ),
                ),
                (
                    "subtitle",
                    models.CharField(
                        blank=True,
                        max_length=127,
                        null=True,
                        validators=[django.core.validators.MaxLengthValidator(127)],
                        verbose_name="Вторичное наименование",
                    ),
                ),
                (
                    "phone_numbers",
                    models.JSONField(default=list, verbose_name="Номера телефонов"),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(500),
                        ],
                        verbose_name="Приоритет контакта",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="static_information.contactsgroups",
                        verbose_name="Группа контактов",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("group", "main_title"),
                        name="unique_contact_group_main_title",
                    )
                ],
            },
        ),
    ]
